package com.marriott.loyalty;
 
global java.util.HashMap<String,HotelAmenity> amenities;

//Any kids > “Family travel” + “Free breakfast” + “Pool”
rule "Booking Has Kids"
    when
       booking : Booking ( numOfKids >= 1, numOfKids: numOfKids )
    then
        System.out.println( "Booking has "+ numOfKids + " kids" );
       	amenities.put("1",HotelAmenity.FAMILY_TRAVEL);
        amenities.put("2",HotelAmenity.FREE_BREAKFAST);
        amenities.put("3",HotelAmenity.POOL);
end

//Single traveler + corp code (IBM) > “Business Center” + “Free high speed Internet”+ “Restaurant on-site”
rule "Single IBM Traveler"

    when
       booking : Booking ( corpCode =="IBM" ,numOfKids==0, numOfAdults==1, adults:numOfAdults)
    then
    	System.out.println("Booking has a single IBM traveler");
        amenities.put("4",HotelAmenity.BUSINESS_CENTER);
        amenities.put("5",HotelAmenity.FREE_HIGH_SPEED_INTERNET);
        amenities.put("6",HotelAmenity.RESTAURANT_ON_SITE);
end

//Stays longer than 7 days > “Kitchen/kitchenette” + “Extended stay”
rule "Stay longer than 7 days"
    when
       booking : Booking ( bookingDuration >7)
    then
    	System.out.println("Booking greater than 7 days");
        amenities.put("8",HotelAmenity.KITCHEN_KITCHENETTE);
        amenities.put("9",HotelAmenity.EXTENDED_STAY);

end
//Any airport hotel (ATLAP, ATLNE, ATLSA, ATLFW, ATLLM, ATLWI) > “Airport shuttle”
rule "Airport Shuttle"
    when
		booking : Booking( hotelCode in ("ATLAP", "ATLNE", "ATLSA", "ATLFW", "ATLLM", "ATLWI"))  
    then
    	System.out.println("Booking greater than 7 days");
        amenities.put("10",HotelAmenity.AIRPORT_SHUTTLE);
	end
//Airport codes (DEN or SFO or ATL or BTV) > "Car rental desk"
rule "Car Rental Desk"
    when
		booking : Booking( airportCode in ("DEN", "SFO", "ATL","BTV"))  
    then
    	System.out.println("Booking greater than 7 days");
        amenities.put("11",HotelAmenity.AIRPORT_SHUTTLE);

end
//Miami, FL > "Beach" + "Airport shuttle"
rule "Miami Hotel"
    when
       booking : Booking ( city=="MIAMI",state =="FL", numOfKids==0)
    then
    	System.out.println("Booking is in Miami");
        amenities.put("12",HotelAmenity.BEACH);
        amenities.put("13",HotelAmenity.AIRPORT_SHUTTLE);
end
//Miami, FL + 2 kids > "Beach" + "Pool" + "Airport shuttle"
rule "Miami Hotel With Kids"
    when
       booking : Booking ( city=="MIAMI",state =="FL", numOfKids==2)
    then
    	System.out.println("Booking is in Miami with 2 kids");
 		
        amenities.put("14",HotelAmenity.BEACH);
        amenities.put("15",HotelAmenity.AIRPORT_SHUTTLE);
        amenities.put("16",HotelAmenity.POOL);
end
//Orlando, FL > "Family travel"
rule "Family Travel"
    when
       booking : Booking ( city=="ORLANDO",state =="FL")
    then
    	System.out.println("Booking is in orlando");
        amenities.put("17",HotelAmenity.FAMILY_TRAVEL);
end
//Augusta, GA > "Golf" + "Pets welcome"
rule "The Masters"
    when
       booking : Booking ( city=="AUGUSTA",state =="GA")
    then
    	System.out.println("Booking is in Augusta GA");
        amenities.put("18",HotelAmenity.GOLF);
        amenities.put("19",HotelAmenity.PETS_WELCOME);

end
//New York, NY > "Parking" + “Airport shuttle”
rule "NYC"
    when
       booking : Booking ( city=="NEW YORK",state =="NY")
    then
    	System.out.println("Booking is in New York");
        amenities.put("20",HotelAmenity.PARKING);
        amenities.put("21",HotelAmenity.AIRPORT_SHUTTLE);
end
//Cancun, MX >> "Resort" + "Pool" + "Airport shuttle"
rule "Cancun"
    when
       booking : Booking ( city=="CANCUN",state =="MX")
    then
    	System.out.println("Booking is in Cancun");
        amenities.put("22",HotelAmenity.RESORT);
        amenities.put("23",HotelAmenity.POOL);
        amenities.put("24",HotelAmenity.AIRPORT_SHUTTLE);
end