package com.marriott.loyatly;

public enum HotelAmenity {
	FAMILY_TRAVEL, FREE_BREAKFAST, POOL, BUSINESS_CENTER, FREE_HIGH_SPEED_INTERNET, RESTAURANT_ON_SITE,
	KITCHEN_KITCHENETTE, EXTENDED_STAY, CAR_RENTAL_DESK, BEACH, GOLF, PETS_WELCOME, PARKING, RESORT, AIRPORT_SHUTTLE

}
